### ISSUE TITLE
【新卡讨论】【fraloow】工程解决方案

### ISSUE THREAD

**Issue by fraloow** [LegacyGwent/LegacyGwent#145]
**新卡描述**
<img src="https://user-images.githubusercontent.com/50948805/84467067-85a93500-acad-11ea-88ab-6061b8e58dd9.png" width="25%" height="25%">

卡名：工程解决方案
品质：银卡
阵营：北方领域
类型：特殊卡
标签：谋略，特殊
效果：生成并打出手牌中一张铜色/银色“机械”卡的原始同名牌，并使其获得3点护甲

设计者：fraloow

设计者的想法：给亨胖亨机械有个底气，用南尼克也算可以，算是绞盘的特异版本

如果后续有修改，可以把修改版本直接加在后面，并加上**update**字样

**Comment by thevemon** [comment]
推荐只能铜卡。
