### ISSUE TITLE
【新卡讨论】【fraloow】戴米恩·图尔

### ISSUE THREAD

**Issue by fraloow** [LegacyGwent/LegacyGwent#147]
**新卡描述**
<img src="https://user-images.githubusercontent.com/50948805/84470254-82b24280-acb5-11ea-81ef-e63b847d440d.png" width="25%" height="25%">

卡名：戴米恩·图尔
品质：银卡
阵营：帝国
类型：单位卡
标签：士兵
战力：7战力
效果：改变一个单位的锁定状态，若其没有被增益则将其战力降至3点。

设计者：fraloow

设计者的想法：降至3点是无视增益的且是红字，可参照奴隶贩子降至1点，这张卡大概是用于对面大白字单位，然后用魅惑类的卡抓过来喂曼德拉，抓人帝国的一个玩具，或者当一个白字的重置哥用。

如果后续有修改，可以把修改版本直接加在后面，并加上**update**字样

**Comment by neal2018** [comment]
【机制】
感觉没啥意思
>这张卡大概是用于对面大白字单位，然后用魅惑类的卡抓过来喂曼德拉，抓人帝国的一个玩具

梦幻combo

**Comment by thevemon** [comment]
理论收益很高，实际情况应该不怎么样
