### ISSUE TITLE
GetRandomCanPlayLocation的效果会导致萝卜迪尔兰士兵被召唤时跳到场上的两张卡之间

### ISSUE THREAD

**Issue by shanzhoupeng** [LegacyGwent/LegacyGwent#15]
可能和以前的游戏机制不同

**Comment by DeusSeuca** [comment]
修改GetRandomCanPlayLocation的Api, 由
CardLocation GetRandomCanPlayLocation(int playerIndex)
修改为
CardLocation GetRandomCanPlayLocation(int playerIndex, bool isAtEnd = false)
如果需要获取随机可打出位置,并且固定在末尾的话,将isAtEnd参数设定为true即可
