### ISSUE TITLE
皇家御令也可以触发萝卜

### ISSUE THREAD

**Issue by shanzhoupeng** [LegacyGwent/LegacyGwent#16]
```@event.Target.Status.Group == Group.Gold && @event.Target.PlayerIndex == Card.PlayerIndex && Card.Status.CardRow.IsInDeck()```中没有对金色单位卡必须从手牌打出的判断

**Comment by shanzhoupeng** [comment]
而且没有加入间谍卡判断 给对面出金鸡会让对面的萝卜跳出来

**Comment by DeusSeuca** [comment]
已经修复,并且相关event类信息得到了补充
