### ISSUE TITLE
【新卡讨论】【fraloow】帕西瓦尔·舒滕巴赫

### ISSUE THREAD

**Issue by fraloow** [LegacyGwent/LegacyGwent#169]
**新卡描述**
<img src="https://user-images.githubusercontent.com/50948805/85672876-e9901c80-b6f5-11ea-9a29-6c08530852e5.png" width="25%" height="25%">

卡名：帕西瓦尔·舒滕巴赫
品质：银卡
阵营：松鼠党
类型：单位卡
标签：侏儒
战力：6战力
效果：将己方手牌所有非“精灵”牌洗回牌组，交换等数量的牌，己方每交换一张牌便获得1点增益

**update version 2.0**
效果：用1张手牌交换牌组中的一张特殊牌，若其稀有度为金色则获得8点增益，稀有度为银色则获得5点增益，稀有度为铜色则获得3点增益

设计者：fraloow

设计者的想法：原本应该是换被揭示的卡洗回去的，发现不咋地还不如做成松鼠党的交换体系

如果后续有修改，可以把修改版本直接加在后面，并加上**update**字样

**Comment by joemej** [comment]
点数太低，效果不够强。同时无法和艾蕾亚斯、维里赫德旅先锋产生配合。另外超过2张的“交换”手牌似乎步子又太大了。
