### ISSUE TITLE
【平衡讨论】七月平衡 反馈接受

### ISSUE THREAD

**Issue by neal2018** [LegacyGwent/LegacyGwent#176]
旧卡的平衡模式决定由平衡部部长安度因 @RealAidenPearce 独裁。

实装逐步进行中。

具体内容如下：

[7月平衡补丁-重做部分-怪兽、帝国、北方.pdf](https://github.com/LegacyGwent/LegacyGwent/files/4869326/7.-.-.pdf)

本issue接受反馈、建议以及批评等

---
你也可以在这里查看详细平衡内容：
<details>
<summary>前言</summary>
DiyGwent 平衡补丁-7 月（重做部分 PART I）

一、前言

哈喽大家好，这里是负责平（bei）衡（guo）的安度因。这次的平衡补丁是 DiyGwent 的第
一个大型平衡，会与之后的平衡不太一样。这次的平衡主要是对于许多几乎 0 出场率的老卡
的增强或重做，当然也会有对主流卡组单卡的相应调整，减少 RNG。我们的 DiyGwent 优势
在于平衡方便，所以希望大家能积极向我反馈意见。各种数值都有待实装测试调整。平衡不
是设计新卡，所以不会有很多特别亮眼的设计，请大家理解~~~~（部分单卡有平衡组注）

</details>

<details>
<summary>怪兽部分</summary>
二、怪兽

暗影长者：领袖，3 战力，吸血鬼，将一个友军非“吸血鬼”单位变为“蝠翼魔”，随后汲
食所有未受伤的敌军单位 1 点战力

_注：我们希望暗影长者与吸血鬼体系更加密切相关，转变无疑是最有吸血鬼文化特色的形式
之一了，因为缺乏 PTR 测试的机会，战力和汲食的数值都有调整空间。_

伊勒瑞斯：7 战力 2 护甲，狂猎，每个回合结束时，将最强的敌方单位移至对方同排并对其
造成 1 点伤害。3 回合后回合开始时，将自身变为“伊勒瑞斯：临终之日”，战力和护甲不
变。

伊勒瑞斯：临终之日：力竭。佚亡。回合结束时，与最强的敌军单位对决。

_注：我们想要对大锤进行一些尝试，让他融入狂猎体系的同时不舍弃好战凶狠的性格，并去
除掉原效果破坏游戏体验的副作用。因此，这个改动将两张伊勒瑞斯合二为一。_

老矛头：昏睡：5 战力，食人魔，使相邻单位获得 1 点增益，自身获得 5 点护甲。每个回合
开始时，若对方同排有至少 3 个单位，则苏醒。

老矛头：苏醒：10 战力，对最多 5 个敌军同排单位造成 2 点伤害。

_注：经典回归。_

戴维娜符文石：炼金，特殊，道具，使牌组中最弱的铜色“怪兽”单位获得 2 点护甲，随后
打出它。

_注：怪兽需要更多滤牌，正好，我们希望改变原来千篇一律的 RNG 符文石，类似戴维娜符
文石，现在各阵营的符文石都有了独特的效果。_

约顿：6 战力，食人魔，对一个敌军单位造成 6 点伤害，若目标被摧毁，在被摧毁的单位同
排降下“刺骨冰霜。”

尼斯里拉：6 战力，狂猎，触发 1 个友方铜色“狂猎”单位的部署效果。

伊芙利特：8 战力，构造体，摧毁 1 个友方铜色/银色单位，然后变为其基础同名牌。

_注：高贵的构造体。_

卢恩：2 战力，类虫生物，诅咒生物，择一：生成“怪物巢穴”；创造 1 个铜色“诅咒生物”。

_注：原效果类似于丹尼斯克莱默，可用的场景过少。_

哥亚特：10 战力，食人魔，摧毁 1 个敌方铜色单位，随后对自身造成等同于被摧毁单位基
础战力的伤害。

_注：是白字伤害，如果大剑被强化了，造成的伤害等于强化后的白字战力。_

帝国蝎尾狮：6 战力 1 护甲，野兽每个己方回合结束时，若自身是场上最强的单位，获得 2
点增益。

蝠魔：2 战力，吸血鬼，汲食一个敌方单位 3 点战力，若其未被摧毁，则自身变为“蝠翼魔”
的原始同名牌。

猫人：3 战力，野兽，诅咒生物，每个回合结束时，若所在排有“满月”恩泽，对最弱的敌
方单位造成 3 点伤害。

寒冰巨人：3 战力 1 护甲，食人魔，回合结束时，若敌方场上有超过 1 排灾厄，召唤 1 张同
名牌至己方近战排。

翼手龙：5 战力，龙兽，吞噬己方墓地中的 1 个铜色单位，并获得其战力的护甲。每个回合
结束时，对自身和同排最弱敌方单位分别造成 2 点伤害。

女蛇妖：10 战力，野兽，若场上任意位置有“血月”，使 1 个友方“野兽”单位获得免疫。

狂猎战士：9 战力，狂猎，将 1 个敌军单位上移一排，若该排上“刺骨冰霜”生效，则对其
造成 2 点伤害。

远古小雾妖：食腐生物，回合结束时，若场上任意位置有“蔽日浓雾”，在自身右侧生成 1
个“小雾妖”的原始同名牌。

狂猎骑士：8 战力，狂猎，场上每有一个其他友方“狂猎单位”，获得 1 点增益。使对方同
排的“刺骨冰霜”伤害提升 1 点。

鹿首魔：14 战力，残物，对自身造成 7 点伤害，每有一个其他友方“怪兽”单位，则减少 1
点伤害。

</details>

<details>
<summary>帝国部分</summary>
三、帝国

暗算：对 2 个敌军单位造成 4 点伤害，对方场上每存在 1 个“间谍”单位，伤害提升 1 点。

叶奈法：死灵法师：6 战力，法师，从己方墓场复活 1 个铜色“士兵”单位。

_注：对原本鸡肋的效果做出了小的修改。_

希拉德：3 战力，军官，魅惑 1 个战力不超过 8 点的“间谍”单位。

_注：顺便提一句，爆牌体系完全移除，所有单卡重做。_

蒂博尔·艾格布拉杰：6 战力，军官，创造 1 个“阿尔巴师”单位，并使其获得 2 点护甲。

_注：阿尔巴师的将领回归初心。因为只有 3 张阿尔巴师单位，所以创造其实是可控的。_

沙斯西乌斯：13 战力，法师，择一：检视对方牌组顶的 3 张牌，将其中 1 张牌置于底端，揭示对方手牌中所有最弱的单位牌。

达兹伯格符文石：炼金，特殊，道具，创造 1 个银色“法师”单位，使其获得佚亡。

_注：看三美女那就是你的问题了，不怪游戏。_

吊死鬼之毒：炼金，特殊，道具，对一个单位造成 5 点伤害，若目标已受伤，则将其摧毁。

_注：新的炼金选择。_

弗林吉拉·薇哥：忠诚/不忠，若被视为间谍，则将自身基础战力设为 2 点。将右侧单位的
战力复制给左侧单位。

_注：薇哥也回归初心了。_

通敌：从对方牌库底打出 1 张铜色/银色牌。

维尔海夫：5 战力，军官，生成 1 个尼弗迦德铜色“机械”单位。

冒牌希里：11 战力，改变敌方打出的下 1 个单位的“间谍”状态。

亚伯力奇：4 战力，法师，抽牌库顶的 1 张铜色/银色“道具”牌，随后打出 1 张铜色牌。

大使：1 战力，间谍，生成 1 个敌方场上铜色单位的原始同名牌。

火蝎攻城弩：添加“驱动：若摧毁目标，则隐匿 1 张牌。”

阿尔巴师枪兵：2 战力，士兵，召唤所有同名牌，若相邻单位均为“士兵”，则使所有同名
牌获得 1 点强化。

作战工程师：5 战力，辅助，使一个 1 个友方机械获得 5 点增益，操控。

射石机：添加“驱动：伤害提高 1 点”。

阿尔巴师装甲骑兵：6 战力，士兵，触发 1 个友方铜色“机械”单位的部署效果。操控。

投尸机：添加“驱动：牛尸倒计时减少 1 回合”。

阿尔巴师矛兵：10 战力，士兵，己方每打出 1 张“士兵”单位牌，使其获得 2 点护甲。

</details>

<details>
<summary>北方部分</summary>
四、北方

雅妲：领袖，4 战力，诅咒生物，生成己方牌库中 1 个北方领域铜色/银色“诅咒生物”的 1
张佚亡基础同名牌。

菲利帕：2 战力，法师，创造 1 张中立铜色/银色“法术”牌。

普希拉：8 战力，辅助，每个回合结束时，治愈最弱的友方单位。

罗契：冷酷之心：5 战力，泰莫利亚，军官，择一：摧毁一个背面向上的伏击敌军单位；从
牌组以伏击状态打出一张铜色北方领域单位，对方放弃跟排后翻开。

丹德里恩：9 战力，辅助，使己方牌库内的非间谍“北方领域”单位获得 1 点增益和 1 点护
甲。

佐李亚符文石：创造 1 个铜色“北方领域”士兵单位，分别属于“泰莫利亚”，“瑞达尼亚”，
“科德温”。

欧德林：7 战力 3 护甲，科德温，士兵，回合开始时，移动至除所在排外己方单位最多的一
排，使同排所有友军单位获得 1 点增益。操控。

福尔泰斯特之傲：8 战力 2 护甲，泰莫利亚，机械，对一个敌军单位造成 2 点伤害，并将其
上移一排。己方每打出 1 个“士兵”单位，再次触发此能力。驱动：伤害提升 1 点。

薇丝：2 战力 1 护甲，士兵，泰莫利亚，生成 1 个铜色“泰莫利亚”单位。

绞盘：从己方墓场中打出 1 张铜色北方领域“机械”牌，并使其获得佚亡。

染血连枷：道具，特殊，造成 5 点伤害，若摧毁目标，则在近战排生成 1 个科德温亡魂的原
始同名牌。

泰莫利亚鼓手：6 战力，泰莫利亚，辅助，使一个友方单位获得 3 点增益和操控。

亚甸槌击者：4 战力，士兵，亚甸，对一个敌军单位造成 4 点伤害，若目标未被摧毁，则对
其再次造成 4 点伤害。

_注：未被摧毁效果只会触发一次，不会重复触发直到单位被摧毁。_

战地医师：4 战力，泰莫利亚，辅助，将 1 个非同名友军铜色单位洗回牌组底端，然后打
出 1 张牌库顶的铜色单位牌。

崔丹姆步兵：10 战力 4 护甲，士兵，回合结束时，若受护甲保护，使相邻友方单位获得 1
点护甲。
</details>

**Comment by WenYuHuaQWQ** [comment]
占个位子，准备对线（

**Comment by neal2018** [comment]
@RealAidenPearce 如果有任何改动可以在本issue内提出

**Comment by fraloow** [comment]
一是整体来看这次与其说是平衡，不如说是使用率偏低的老卡重做，没有任何一张比较强的卡削弱
二是大多数卡的强度和模型未经过实测貌似看起来比较低，也有部分卡机制比较难说

怪兽阵营方面，吸血鬼体系最好不要围绕蝠翼魔，而是围绕关键词
帝国阵营方面，没啥亮点，投尸机算是比较可，而去掉爆牌也较为争议吧
北方阵营方面，多多少少都有其它旧卡的既视感或创造生成比较多

**Comment by lwr511** [comment]
diy的工作量令人感动，首先感谢！
我认为所有重做卡都应做成新卡，把老卡保留。
老卡的改动最好是：1.数值改动 2.增加额外效果 3.出新的配合卡
因为做新卡的工作量和改老卡完全一致

**Comment by llfsm** [comment]
以下几张卡个人觉得有问题
卢恩：银卡生成银卡，完爆掉了怪物巢穴
大锤：堂堂大锤上场只有8加一位移收益，被银卡法师电单杀
鹿首魔：白字过高，配合食尸鬼过于超模
暗算：原来的一张好用解，现在绑定间谍，而且只有长局有用、铺垫要求过高，不能及时处理掉对面引擎
菲丽芭：中立版狐妖
以下几张卡建议直接做新卡
约顿：霜怪不需要太多的霜，原来的3位移相当实用
大使：契拉克出原版大使保护铁卫也不失为一种选择

平衡总体做的还行，GIT用的不熟练，就不排版了

**Comment by neal2018** [comment]
1
 >蒂博尔·艾格布拉杰：6 战力，军官，创造 1 个“阿尔巴师”单位，并使其获得 2 点护甲。

25哥原效果挺有意思，并且现在爆牌不带25哥，可以考虑保留原卡

2
>菲利帕：2 战力，法师，创造 1 张中立铜色/银色“法术”牌。

不建议创造

3
帝国有必要加入驱动体系吗？

**Comment by newhandapo** [comment]
赞同或者修改后赞同的效果如下，其他本人实名反对：
帝国蝎尾狮：每个己方回合结束时，若自身是场上最强的单位，获得 2点增益。
福尔泰斯特之傲：对一个敌军单位造成 2 点伤害，并将其上移一排。己方每在同排打出 1 个“士兵”单位，再次触发此能力。驱动：伤害提升 1 点。
绞盘：择一：从己方墓场中打出 1 张铜色北方领域“机械”牌，并使其获得佚亡。或所有己方机械+3增益。
亚甸槌击者：4 战力，士兵，亚甸，对一个敌军单位造成 4 点伤害，若目标未被摧毁，则对其再次造成 4 点伤害。

**Comment by WenYuHuaQWQ** [comment]
我代伯约发一下建议

暗影长者 5分
节奏是3领袖-被变形单位+5变成蝠翼摩+所有对面未受伤单位×2，这是怪兽长局上限最高的卡，就算是面对增益牌组也依然可以打出很多点数，惧怕的反而是对面没几个单位的牌组，但是说实话有点诡异，为什么不是自己吸而是搞一个友军单位让它吸？这是什么意境？下限很丢人，上限很离谱，让它成为敢在r2逼牌的领袖，也是真正意义上蝠翼摩的新领袖。

**Comment by thevemon** [comment]
1.大锤直接改成摧毁一个处于冰霜里面的单位就够了，太强的话削点战力就好。把两个大锤融在一起效果不是很好，真的。
2.尼斯里拉效果一直可以，作为一个狂猎少有的前期去除单位，收益也很不错，没人用纯粹是因为狂猎本身太弱了。
3.卢恩没人用是因为类虫和诅咒生物在怪物里面不多。以后类虫多出来的时候就有用了(我还特地组了一个卡组效果还不错，真的，就是差了一张点数高的类虫或诅咒生物)
4.冰霜巨人应该改成回合开始时有效，再加点护甲和战力。回合结束就召一个，你不如直接全拉出来。或者说每有一个单位被冰霜摧毁就拉一个也不错。
5.鹿首魔建议改成削弱

**Comment by thevemon** [comment]
1.25哥并不是爆牌的核心金卡，但是是其他套路的核心金卡，不用改。
2.观星哥2效果揭示基本上不带，1效太拉胯也基本上没人带，不如复制三国杀的诸葛亮，选择看我方还是对方的三张牌，按任意顺序放牌顶或牌底。
3.符文石就别创造了，直接拉卡组里的法师就好，反正帝国的法师都是功能型的也没啥检索手段。
4.冒牌希里新效果不如渗透者实用，建议按原效果改:每回合开始随机增益对方场上一个单位2点。遗愿:摧毁同排战力最大的一个单位。
5.维尔海夫效果不错，一般常规揭示都会带，不用改。要改的是福德姆林。
6.作战工程师我一直用，觉得弱的话加点战力就可以了，不用这么大改。
7.阿尔巴师装甲骑兵和北方的工程师冲突了，还弱了许多，建议换成别的效果。
8.阿尔巴师矛兵这不是在给护甲北做内奸吗？建议换成别的效果。

**Comment by thevemon** [comment]
1.普西拉改成受伤的战力最小的单位，不然很很可能大部分时候都是二愣子。
2.菲利帕想不出效果的话以后再改吧，老创造这个那个的有意思吗？
3.微丝本身的调度效果不错改成以前每有军官或者士兵多加一次就可以了。何况我40北也经常带。
4.鼓手最好自身也带个操控。

**Comment by joemej** [comment]
怪兽篇：
1、约顿的效果不建议调整。首先致死打霜的意义不大，会降低霜的收益。其次本身约顿的位移特效很契合霜怪。
2、卢恩生成怪物巢穴不妥。这样就没人带怪物巢穴了。
3、老板哥亚特可以作为后手的银卡爆发（霜怪缺少无铺垫的银卡爆发，虽然哥亚特也不是很好用），新哥亚特建议作为新卡，而不是重做。
4、猫人差评。3点3收益的引擎是想重蹈【科德温亡魂】的覆辙吗。女蛇妖和猫人的构筑似乎收益太大。单纯的女蛇妖也没有很好的配合（女夜魔应该不用配合）
5、远古小雾妖差评，强度比科德温亡魂还高。
6、狂猎骑士好评，融合了寒霜巨人的功能。
7、鹿首魔的基础点数过高。配合食尸鬼容易爆炸。建议将“伤害自身”改为“削弱自身”

帝国篇：（帝国的操控和驱动好评）
1、暗算的强度不足金卡。算上对方半场4间谍单位时（3特使，1渗透者标记），才能16点收益。
2、希拉德重做：好评，爆牌体系完全移除，兹磁。
3、吊死鬼之毒：强度过低。比金卡【维伯约恩】少了11点。
4、维尔海夫描述不规范，若是随机生成1张机械则强度尚可。若是3选1则配合间谍可能强度过高，比弗林姆德稳定太多了。

北方篇：
1、菲莉帕·狐妖，设计没新意。老菲莉帕作为金卡点数的模型标杆，可以不用调整。
2、罗契·冷酷之心：如何解读伏击和部署的互动。
3、欧德林：点数过高，必须一张雷劈死。
4、绞盘：非常好的想法，兹磁。
5、战地医生：老战地医生已经回归了，不需要修改。
6、崔丹姆步兵：很有意思的设计。但强度似乎不足以进入现有构筑。

**Comment by anorthcat** [comment]
【怪兽】
暗影长者：领袖，3 战力，吸血鬼，将一个友军非“吸血鬼”单位变为“蝠翼魔”，随后汲
食所有未受伤的敌军单位 1 点战力
【领袖彻底绑定一个体系不太可取，而且带蝠翼魔的体系，讲道理不会有太多的未受伤单位】

伊勒瑞斯：7 战力 2 护甲，狂猎，每个回合结束时，将最强的敌方单位移至对方同排并对其
造成 1 点伤害。3 回合后回合开始时，将自身变为“伊勒瑞斯：临终之日”，战力和护甲不
变。
伊勒瑞斯：临终之日：力竭。佚亡。回合结束时，与最强的敌军单位对决。
【不建议合并在一起，大锤的打伤害可以略微加强，大锤这个位移的效果我觉得好，变身就没啥必要】

戴维娜符文石：炼金，特殊，道具，使牌组中最弱的铜色“怪兽”单位获得 2 点护甲，随后
打出它。
【护甲不如增益，怪兽要护甲没用】

约顿：6 战力，食人魔，对一个敌军单位造成 6 点伤害，若目标被摧毁，在被摧毁的单位同
排降下“刺骨冰霜。”
【没必要改】

伊芙利特：8 战力，构造体，摧毁 1 个友方铜色/银色单位，然后变为其基础同名牌
【类似于北方的诅咒骑士，但可以跟遗愿配合，但是感觉不会很赚】

卢恩：2 战力，类虫生物，诅咒生物，择一：生成“怪物巢穴”；创造 1 个铜色“诅咒生物”。
【完爆怪物巢穴，不得行】

帝国蝎尾狮：6 战力 1 护甲，野兽每个己方回合结束时，若自身是场上最强的单位，获得 2
点增益。
【银卡的2点引擎，触发的话估计要用寄生虫增益才行吧，自身点数太小，不喜欢这样的设计】

蝠魔：2 战力，吸血鬼，汲食一个敌方单位 3 点战力，若其未被摧毁，则自身变为“蝠翼魔”
的原始同名牌。
【这个与蝠翼魔绑定的感觉没必要，不缺蝠翼魔，缺跟蝠翼魔配合的卡养蝠翼魔】

猫人：3 战力，野兽，诅咒生物，每个回合结束时，若所在排有“满月”恩泽，对最弱的敌
方单位造成 3 点伤害。
【这个3点引擎，不解爆炸，差评，类比科德温亡魂】

寒冰巨人：3 战力 1 护甲，食人魔，回合结束时，若敌方场上有超过 1 排灾厄，召唤 1 张同
名牌至己方近战排。
【很弱，而且没必要搞那么多一拖二】

女蛇妖：10 战力，野兽，若场上任意位置有“血月”，使 1 个友方“野兽”单位获得免疫。
【差评，给野兽上免疫没必要】

狂猎战士：9 战力，狂猎，将 1 个敌军单位上移一排，若该排上“刺骨冰霜”生效，则对其
造成 2 点伤害。
【狂猎版水鬼，不得行，还不如水鬼好用】

远古小雾妖：食腐生物，回合结束时，若场上任意位置有“蔽日浓雾”，在自身右侧生成 1
个“小雾妖”的原始同名牌。
【4点引擎，离谱，类比科德温亡魂】

鹿首魔：14 战力，残物，对自身造成 7 点伤害，每有一个其他友方“怪兽”单位，则减少 1
点伤害。
【这是个残物，为啥要跟野兽配合】

【帝国】
三、帝国
暗算：对 2 个敌军单位造成 4 点伤害，对方场上每存在 1 个“间谍”单位，伤害提升 1 点。
【下限更低，一般上限5-6个间谍，比以前提高2点伤害，弱了吧】

希拉德：3 战力，军官，魅惑 1 个战力不超过 8 点的“间谍”单位。
【不如改为 交换牌库顶的卡牌，加强基础战力】

蒂博尔·艾格布拉杰：6 战力，军官，创造 1 个“阿尔巴师”单位，并使其获得 2 点护甲。
【其实就是生成，但是25哥没必要改，因为失去了爆牌体系，25哥只是一个正常的点数金卡】

沙斯西乌斯：13 战力，法师，择一：检视对方牌组顶的 3 张牌，将其中 1 张牌置于底端，揭示对方手牌中所有最弱的单位牌。
【揭示内战杀手，把对面的揭示士兵揭示出来，第一个效果可以配合我说的希拉德改动偷卡，甚至可以加强一点，也看自己牌库的三张选一张置底】

吊死鬼之毒：炼金，特殊，道具，对一个单位造成 5 点伤害，若目标已受伤，则将其摧毁。
【群岛的斩杀哥银卡版本，更弱了，毒蛇基本不会留活口，估计不会带】

弗林吉拉·薇哥：忠诚/不忠，若被视为间谍，则将自身基础战力设为 2 点。将右侧单位的
战力复制给左侧单位。
【早回归初心了】

冒牌希里：11 战力，改变敌方打出的下 1 个单位的“间谍”状态。
【银卡渗透没必要，甚至要让对面决定】

火蝎攻城弩：添加“驱动：若摧毁目标，则隐匿 1 张牌。”
【没必要给帝国加驱动效果】

阿尔巴师枪兵：2 战力，士兵，召唤所有同名牌，若相邻单位均为“士兵”，则使所有同名
牌获得 1 点强化。
【太弱了，而且一拖二之前也提过更好的方案】

作战工程师：5 战力，辅助，使一个 1 个友方机械获得 5 点增益，操控。
【没必要给帝国加驱动效果】

射石机：添加“驱动：伤害提高 1 点”。
【没必要给帝国加驱动效果】

阿尔巴师装甲骑兵：6 战力，士兵，触发 1 个友方铜色“机械”单位的部署效果。操控。
【没必要给帝国加驱动效果】

投尸机：添加“驱动：牛尸倒计时减少 1 回合”。
【没必要给帝国加驱动效果】

【北方】
菲利帕：2 战力，法师，创造 1 张中立铜色/银色“法术”牌。
【已经有狐妖了】

普希拉：8 战力，辅助，每个回合结束时，治愈最弱的友方单位。
【北方增益多绿字，治愈给群岛用】

罗契：冷酷之心：5 战力，泰莫利亚，军官，择一：摧毁一个背面向上的伏击敌军单位；从
牌组以伏击状态打出一张铜色北方领域单位，对方放弃跟排后翻开。
【效果二伏击不触发部署效果，点数最大就是10，完全没必要伏击】

丹德里恩：9 战力，辅助，使己方牌库内的非间谍“北方领域”单位获得 1 点增益和 1 点护
甲。
【原有的效果就可以的，这样不是更弱了吗】

福尔泰斯特之傲：8 战力 2 护甲，泰莫利亚，机械，对一个敌军单位造成 2 点伤害，并将其
上移一排。己方每打出 1 个“士兵”单位，再次触发此能力。驱动：伤害提升 1 点。
【过强】

薇丝：2 战力 1 护甲，士兵，泰莫利亚，生成 1 个铜色“泰莫利亚”单位。
【没必要改】

染血连枷：道具，特殊，造成 5 点伤害，若摧毁目标，则在近战排生成 1 个科德温亡魂的原
始同名牌。
【上下限极大，也就是必须致死才有收益，完全可以看有条件点数更高的亡魂，反对】

泰莫利亚鼓手：6 战力，泰莫利亚，辅助，使一个友方单位获得 3 点增益和操控。
【给机械操控，意境警察表示反对，而且也没有必要搞那么多操控】

亚甸槌击者：4 战力，士兵，亚甸，对一个敌军单位造成 4 点伤害，若目标未被摧毁，则对
其再次造成 4 点伤害。
【这效果实际上就是打8，再改改吧】

战地医师：4 战力，泰莫利亚，辅助，将 1 个非同名友军铜色单位洗回牌组底端，然后打
出 1 张牌库顶的铜色单位牌。
【已经有了，现有医师也很强，没必要改】
