### ISSUE TITLE
缺少操控api

### ISSUE THREAD

**Issue by shanzhoupeng** [LegacyGwent/LegacyGwent#18]
操控是可以被锁定的能力

**Comment by DeusSeuca** [comment]
目前还没有对"操控"的良好支持,近期会试着加入

**Comment by DeusSeuca** [comment]
已经添加操控相关的api,应该已经足以实现目前的功能, 如果有更好的api建议欢迎提新的issue
(使用GameCard.GetCrewdCount来获取场上指定卡牌周围单位提供的操控数量)
注意,如果对非场上单位使用该方法会引起异常
