### ISSUE TITLE
【新卡讨论】【fraloow】猩红诅咒

### ISSUE THREAD

**Issue by fraloow** [LegacyGwent/LegacyGwent#180]
**新卡描述**
<img src="https://user-images.githubusercontent.com/50948805/86894712-06851080-c136-11ea-9282-94821107ca19.png" width="25%" height="25%">

卡名：猩红诅咒
品质：金卡
阵营：怪兽
类型：特殊卡
标签：有机
效果：择一：己方场上每有一道“月光”便在对方半场同排生成相同数量的“血月”；敌方场上每有一道“血月”便在己方半场同排生成相同数量的“满月”；从牌组打出2张“月光”。

设计者：fraloow

设计者的想法：可以在此处说说为什么设计这张卡。

如果后续有修改，可以把修改版本直接加在后面，并加上**update**字样

**Comment by anorthcat** [comment]
卡名：猩红诅咒
品质：银卡
阵营：怪兽
类型：特殊卡
标签：恩泽/灾厄
择一：在己方两排生成月光；在敌方两排生成血月
