### ISSUE TITLE
【新卡讨论】倒计时体系尝试（持续更新）

### ISSUE THREAD

**Issue by cattermore** [LegacyGwent/LegacyGwent#198]
**新卡描述**
![image](https://user-images.githubusercontent.com/57998451/88074630-3d353f00-cbaa-11ea-926a-4bb185adfbfb.png)

卡名：收获日
品质：铜卡
阵营：中立
类型：特殊卡
效果：在双方同排生成一张“贡品”。

衍生物：
![image](https://user-images.githubusercontent.com/57998451/88074655-47efd400-cbaa-11ea-90cb-b5514b7bd4a3.png)

衍生物：贡品
品质：铜卡
阵营：中立
类型：单位卡
标签：衍生物 退场
战力：4点
效果：倒计时2：2回合后，己方回合结束时，使敌方1个随机单位获得12点增益。

![image](https://user-images.githubusercontent.com/57998451/88355841-89de6d00-cd98-11ea-9e93-8653c849546d.png)

卡名：法师渗透者
品质：铜卡
阵营：尼弗迦德
类型：间谍 法师
效果：使左侧的单位的倒计时效果增加1回合。

**Comment by anorthcat** [comment]
1、女间谍打出去就是亏点的，倒计时+1只能延迟一回合，负点数卡
2、收获日双方都有等于，大家点数一样的，零点数卡
3、倒计时体系，首先是需要设计一个核心的点数引擎，以倒计时改变，倒计时-1，倒计时+1等类似作为触发条件涨点，建议是倒计时改变。同时需要有持续循环的倒计时，比如说设计一个 倒计时2：回合开始时对随机敌方单位造成xx点伤害，触发后重新计时；这样或可以设计打出至己方场上的倒计时卡配合，也可以设计减少同排所有单位倒计时这样的卡，作为配合卡，每次的倒计时改变都能有足够的收益支撑，剩下的就是金银卡的塑造以及可以设计一些倒计时卡提高保护能力或者骗解，以此为一整个体系；
4、然后说说倒计时体系的特点，以现有的倒计时卡来看，大多都是高风险高收益的卡，比如白龙比如女夜魔，一个可以创造一卡卡差，一个可以奠定胜局，但同时他们都非常容易被解。如果出倒计时的卡，那么相应的就需要平衡倒计时的收益，收益高的风险就高，收益低的可以提高生存能力，至于对倒计时单位的保护，则需要再酌情考虑了，有些难以平衡
