### ISSUE TITLE
对于“返回卡组”不同的卡用了不同的api

### ISSUE THREAD

**Issue by shanzhoupeng** [LegacyGwent/LegacyGwent#22]
猫女是ShowCardMove，希里冲刺时Resurrect。

**Comment by DeusSeuca** [comment]
之所以调用了不同api是因为,在原昆特里面对于"洗回卡组/返回卡组"具体会产生的事件很模糊,凭感觉来讲希里冲刺更像是"复活",而猫女仅仅是把卡牌置入卡组这样一个单纯的行为, 具体使用哪种方法如果没有相关资源很难有明确的判定,如果有建议或者素材欢迎提议
