### ISSUE TITLE
在选牌界面卡住 不能确认

### ISSUE THREAD

**Issue by shanzhoupeng** [LegacyGwent/LegacyGwent#43]
例如女祭司 或者老奶奶 选择一张牌复活时 卡住 不能确认 此时可以选择多张牌 但是无论选几张牌 都不能确认

**Comment by DeusSeuca** [comment]
目前版本已经修复, 老版本防止措施:"在每局的调度阶段,如果点击调度结束按钮,切勿点击多次"
