### ISSUE TITLE
黑血的效果1（创造）似乎没有增益2点

### ISSUE THREAD

**Issue by shanzhoupeng** [LegacyGwent/LegacyGwent#6]
if (switchCard == 0)
            {
                var cards = GwentMap.GetCreateCardsId(x => x.Group == Group.Copper &&
                        (x.Categories.Contains(Categorie.Necrophage) ||
                        x.Categories.Contains(Categorie.Vampire)), Game.RNG).ToArray();
                return await Game.CreateAndMoveStay(PlayerIndex, cards, isCanOver: true);
            }

**Comment by DeusSeuca** [comment]
感谢提出bug,目前已解决~
