### ISSUE TITLE
呢喃山丘似乎不能创造银卡

### ISSUE THREAD

**Issue by shanzhoupeng** [LegacyGwent/LegacyGwent#7]
public override async Task<int> CardPlayEffect(bool isSpying, bool isReveal)
        {
            var ids = GwentMap.GetCreateCardsId(x => x.Is(Group.Copper, filter: x => x.HasAllCategorie(Categorie.Organic)), Game.RNG);
            return await Game.CreateAndMoveStay(PlayerIndex, ids.ToArray());
        }

**Comment by DeusSeuca** [comment]
感谢提出bug,目前已解决~
